services:
  - type: web
    name: robo-raksha-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
